<?php
$headTitle = 'Categories';
$this->headTitle($headTitle);
?>
<h3><?= $this->escapeHtml($headTitle) ?></h3>
<br>
<div><a href="<?= $this->url('admin/category', ['action' => 'add']) ?>" class="btn btn-default">Add category</a></div>
<br>
<?php if (! $this->categories) : ?>
<h5>List is empty</h5>
<?php else : ?>
<div class="table-responsive">
    <table class="table table-hover table-striped">
        <tr>
            <th>#</th>
            <th>Category key</th>
            <th>Category name</th>
            <th>Actions</th>
        </tr>
        <?php $i = 0 ?>
        <?php foreach ($this->categories as $category) : ?>
        <tr>
            <td><?= ++$i ?></td>
            <td><?= $this->escapeHtml($category->getCategoryKey()) ?></td>
            <td><?= $this->escapeHtml($category->getCategoryName()) ?></td>
            <td>
                <a href="<?= $this->url('admin/category', ['action' => 'edit', 'id' => (int)$category->getId()]) ?>">
                    Edit
                </a>
                &nbsp;&nbsp;|&nbsp;&nbsp;
                <a href="<?= $this->url('admin/category', ['action' => 'delete', 'id' => (int)$category->getId()]) ?>"
                   onclick="return confirm('Are You sure?')"
                >
                    Delete
                </a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>
<?php endif; ?>
