<?php
$headTitle = 'Admin';
$this->headTitle($headTitle);
?>
<div class="row">
    <div class="col-xs-6">
        <h3><?= $this->escapeHtml($headTitle) ?></h3>
    </div>
    <div class="col-xs-6">
        <div class="breadcrumb-box">
        <?= $this->navigation('navigation')->breadcrumbs()->setminDepth(1)->setPartial('partial/breadcrumb') ?>
        </div>
    </div>
</div>
<p>You have the following capabilities:</p>
<ul class="list-unstyled">
    <li><a href="admin/category">Manage categories</a></li>
    <li><a href="admin/article">Manage articles</a></li>
    <li><a href="admin/comment">Manage comments</a></li>
</ul>
<br>
